Partially resolve Issue #{40}
bellesamways/studynotes pull request #47
Opened 2020-10-10 00:32 UTC by naslausky

Adiciona aula 6 de Linguagem de Programação - Java

2020-10-13 17:31 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula6.md
> +| private         | ✅      | ❌      | ❌         | ❌     |
ficou top a tabelinha com emoji!

2020-10-13 17:34 UTC, bellesamways requested changes
só uma pequena mudancinha :D

2020-10-13 17:34 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula6.md
> +__Final__: Pode ser aplicado em classes, métodos e atributos. Indica que esta é a última atribuição ou definição da estrutura. Não será permitida uma nova re-escrita. Para uma classe, não há herança
aqui é legal pular uma linha após a parte do Abstract, se não o md deixa tudo na mesma linha.

2020-10-13 22:19 UTC, naslausky commented
Corrigi o que foi pedido! Poderia dar uma olhada agora?
Obrigado.

2020-10-14 13:39 UTC, bellesamways approved these changes
perfeito, obrigada!

2020-10-14 13:39 UTC, merged

2020-10-14 14:35 UTC, johnsjohns commented
Muito obrigado!!