Resolve Issue #40
bellesamways/studynotes pull request #50
Opened 2020-10-14 15:55 UTC by johnsjohns

Closes #40

2020-10-18 22:42 UTC, bellesamways requested changes
oi! gostei bastante de como ficou! pedi só alguns ajustezinhos, uns espaços que ficaram faltando para ser mais legível :D

um abraço!

2020-10-18 22:42 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula10.md
> +**Definição:** Um Java Bean é um componente de software reutilizável, que pode ser manipulado visualmente por uma ferramenta de desenvolvimento”
faltou só um enterzinho entre os tópicos :D

2020-10-18 22:42 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula8.md
> +**Um sistema orientado a objetos é definido como um conjunto de objetos interagindo ou trocando mensagens**. Os eventos representam as ações dos atores nesse processo ou alguma resposta a uma mudança
um enterzinho aqui tbm :)

2020-10-18 22:42 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula8.md
> +**ActionListener** - interface que especifica os objetos que tratam eventos do tipo ActionEvent. existem várias soluções possíveis para tratar o evento:
um enterzinho aqui tbm

2020-10-18 22:42 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula9.md
> +Por outro lado, instâncias de Exception, ou de qualquer outra de suas subclasses, são **verificadas (checked)** como, p.ex, IOException, ClassNotFoundException e CloneNotSupportedException. Elas repr
um enterzinho entre os parágrafos :D

2020-10-18 22:42 UTC, bellesamways commented on Faculdade/Linguagem-de-Programacao-Java/Aula9.md
> +
um enterzinho aqui tbm, entre a 103 e a 104

2020-10-20 22:20 UTC, bellesamways approved these changes
tudo certo, obrigada! ❤️

2020-10-20 22:20 UTC, merged

2020-10-21 12:39 UTC, johnsjohns commented
Muito obrigado, me ajudou muito a melhorar minhas skills no github

2020-10-21 13:16 UTC, bellesamways commented
> Muito obrigado, me ajudou muito a melhorar minhas skills no github

nao tem de que <3